# url = "https://rpc.helius.xyz/?api-key=7df1283e-42ff-42dd-8a74-2ca2883178dd"
[test.validator]
url = "https://api.metaplex.solana.com/"

# Whirlpool Program
[[test.validator.clone]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "local_deploy/whirlpool.so"

# Whirlpool Config
[[test.validator.clone]]
address = "2LecshUwdy9xi7meFgHtFJQNSKk4KdTrcpvaB56dP2NQ"

# Whirlpool Fee Tier 64
[[test.validator.clone]]
address = "HT55NVGVTjWmWLjV7BrSMPVZ7ppU8T2xE5nCAZ6YaGad"

# Whirlpool Fee Tier 128
[[test.validator.clone]]
address = "BGnhGXT9CCt5WYS23zg9sqsAT2MGXkq7VSwch9pML82W"

# Pyth Btc Price Feed
[[test.validator.clone]]
address = "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU"

# Super User ATA Samo [22 Samo Balance]
[[test.validator.clone]]
address = "7MmzTYgGM8yX8yMPWngEx8rK7ZX2hU7h9P4Ez16WPUQB"

# Super User ATA USDC [0.1 USDC Balance]
[[test.validator.clone]]
address = "2pJxmcoBT9vd2uxfL84e8NseFABt9Mx7P6DreSBRVME3"

# Test User ATA Samo [22 Samo Balance]
[[test.validator.clone]]
address = "AwVXdVdkXTvSA7ja3gDYfLDRmkMafsMzoJoBowA2AMdL"

# Test User ATA USDC [0.1 USDC Balance]
[[test.validator.clone]]
address = "E13JZKB5iDX4D85s2S95fBusbquKphejXnX4WnEkm4ej"

# SAMO Mint
[[test.validator.clone]]
address = "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU"

# USDC Mint
[[test.validator.clone]]
address = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v"

[features]
seeds = false
skip-lint = false
[programs.localnet]
vayoo_contracts = "6ccnZSaDcMwKe1xwHbubs4q2GdPEr7hSK59A3GddJpte"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/testKeys/testUser.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 100_000