# url = "https://rpc.helius.xyz/?api-key=7df1283e-42ff-42dd-8a74-2ca2883178dd"
[test.validator]
url = "https://api.metaplex.solana.com/"

# Whirlpool Program
[[test.validator.clone]]
address = "whirLbMiicVdio4qvUfM5KAg6Ct8VwpYzGff3uctyCc"
program = "local_deploy/whirlpool.so"

# Whirlpool Config
[[test.validator.clone]]
address = "2LecshUwdy9xi7meFgHtFJQNSKk4KdTrcpvaB56dP2NQ"

# Whirlpool Fee Tier 64
[[test.validator.clone]]
address = "HT55NVGVTjWmWLjV7BrSMPVZ7ppU8T2xE5nCAZ6YaGad"

# Whirlpool Fee Tier 128
[[test.validator.clone]]
address = "BGnhGXT9CCt5WYS23zg9sqsAT2MGXkq7VSwch9pML82W"

# Pyth Btc Price Feed
[[test.validator.clone]]
address = "GVXRSBjFk6e6J3NbVPXohDJetcTjaeeuykUpbQF8UoMU"

[features]
seeds = false
skip-lint = false
[programs.localnet]
vayoo_contracts = "6ccnZSaDcMwKe1xwHbubs4q2GdPEr7hSK59A3GddJpte"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "./tests/testKeys/testUser.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
deploy-idl="anchor build; ./migrations/deploy-idl.sh"

[test]
startup_wait = 100_000